name: Manual Patch
permissions: write-all
env:
  repository: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  org_input: ${{ inputs.org }}
  org_event_input: ${{ github.event.inputs.org }}
on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Which "Revanced" do you want to patch?'
        required: true
        default: 'Revanced'
        type: choice
        options:
          - 'Revanced Extended'
  workflow_call:
    inputs:
      org:
        required: true
        type: string
jobs:
  patch_rve:
    name: Patch Revanced Extended Stable
    if: ${{ github.event.inputs.org == 'Revanced Extended' || inputs.org == 'Revanced Extended' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rve
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rve
        if: steps.check-gh-rve.outputs.internet_error == '0'
        run: bash src/build/Revanced-Extended.sh 1
      - name: Cache
        uses: actions/upload-artifact@v4
        with:
          name: Cache-apk
          path: |
            download
      - name: Releasing APK files
        id: release-rve
        if: steps.check-gh-rve.outputs.internet_error == '0'
        uses: ./.github/actions/release
  patch_rve_:
    name: Patch Revanced Extended Stable
    needs: patch_rve
    if: ${{ github.event.inputs.org == 'Revanced Extended' || inputs.org == 'Revanced Extended' }}
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Cache
        uses: actions/download-artifact@v4
        with:
          name: Cache-apk
      - name: Package Manager
        run: |
             $global:progressPreference = 'silentlyContinue'
             Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
      - name: Ngrok
        run: |
             $global:progressPreference = 'silentlyContinue'
             Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
             Expand-Archive ngrok.zip
             .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      - name: Enable Remote Desktop
        run: |
             $global:progressPreference = 'silentlyContinue'
             Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
             Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
             Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      - name: Run
        run: |
             $global:progressPreference = 'silentlyContinue'
             $Pwd = -join ('abcdefghkmnrstuvwxyzABCDEFGHKLMNPRSTUVWXYZ23456789$%&*#'.ToCharArray() | Get-Random -Count 32)
             Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText $Pwd -Force)
             Start-Process -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp 3389"
             Start-Sleep -s 10
             $Response = ConvertFrom-Json(Invoke-WebRequest -Uri "http://127.0.0.1:4040/api/tunnels")
             Start-Sleep -s 1
             $URLString = $Response.tunnels.public_url
             $Fulladdress = ($URLString -split "tcp://")[1]
             $Rdp = "full address:s:$Fulladdress`nusername:s:runneradmin"
             $ProgressPreference = 'Continue'
             echo "RDP INFOMATION"
             echo "Fulladress: $Fulladdress"
             echo "User: runneradmin"
             echo "Pwd: $Pwd"
      - name: Set Timeout 6 hours
        run: |
             $global:progressPreference = 'silentlyContinue'
             Start-Sleep -s 21600
